name: fhir_bulk
description: A Dart/Flutter package for working with FHIR bulk data. Also includes ability to archive.
version: 0.11.3
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir_bulk

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  archive: ^3.4.5
  fhir: ^0.11.4
  # fhir:
  #   path: ../fhir
  freezed_annotation: ^2.4.1
  http: ^1.1.0
  json_annotation: ^4.8.1
  mime: ^1.0.4
  universal_io: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.3
  import_sorter: ^4.6.0
  json_serializable: ^6.7.1
  test: ^1.24.7