name: fhir_bulk
description: A Dart/Flutter package for working with FHIR bulk data. Also includes ability to archive.
version: 0.11.1
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir_bulk

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  archive: ^3.3.7
  fhir: ^0.11.2
  # fhir:
  #   path: ../fhir
  freezed_annotation: ^2.2.0
  http: ^1.0.0
  json_annotation: ^4.8.1
  mime: ^1.0.4
  universal_io: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.5
  freezed: ^2.3.5
  import_sorter: ^4.6.0
  json_serializable: ^6.7.0
  test: ^1.24.3